// @generated by tauri-specta from the Rust types. Do not edit.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	hardwareInfo: () => __TAURI_INVOKE<HardwareInfo>("hardware_info").then((v) => (({...v,backends:v.backends.map(i=>i)}) as typeof v)),
	/**  Full configuration of every preset, so the Setup screen can show and edit them. */
	presetConfigs: () => __TAURI_INVOKE<PresetConfig[]>("preset_configs"),
	recommendPreset: (datasetId: number | null) => __TAURI_INVOKE<Recommendation>("recommend_preset", { datasetId }),
	/**  Predicted cost of a configuration on this computer. Cheap enough to call on every edit. */
	estimateRun: (model: ModelConfig, train: TrainConfig, datasetId: number | null) => __TAURI_INVOKE<Estimate>("estimate_run", { model, train, datasetId }),
	/**  Where the app's disk space goes: datasets, saved models, chats and the database. */
	storageUsage: () => __TAURI_INVOKE<StorageUsage>("storage_usage"),
	createRun: (req: CreateRunRequest) => __TAURI_INVOKE<RunSummary>("create_run", { req: ({...req,model:req.model==null?req.model:req.model,train:req.train==null?req.train:req.train,goal:req.goal==null?req.goal:req.goal}) }).then((v) => (({...v,bestHeldoutNats:v.bestHeldoutNats==null?v.bestHeldoutNats:v.bestHeldoutNats,lastHeldoutNats:v.lastHeldoutNats==null?v.lastHeldoutNats:v.lastHeldoutNats,lastTrainNats:v.lastTrainNats==null?v.lastTrainNats:v.lastTrainNats,goal:v.goal==null?v.goal:v.goal}) as typeof v)),
	/**  Continue a run's saved model as a new run, with different settings or text. The new run starts from the save. */
	forkRun: (req: ForkRunRequest) => __TAURI_INVOKE<RunSummary>("fork_run", { req: ({...req,train:req.train==null?req.train:req.train,goal:req.goal==null?req.goal:req.goal}) }).then((v) => (({...v,bestHeldoutNats:v.bestHeldoutNats==null?v.bestHeldoutNats:v.bestHeldoutNats,lastHeldoutNats:v.lastHeldoutNats==null?v.lastHeldoutNats:v.lastHeldoutNats,lastTrainNats:v.lastTrainNats==null?v.lastTrainNats:v.lastTrainNats,goal:v.goal==null?v.goal:v.goal}) as typeof v)),
	/**  Start a run, or continue it from its latest checkpoint when it has one. */
	startRun: (runId: number) => __TAURI_INVOKE<RunSummary>("start_run", { runId }).then((v) => (({...v,bestHeldoutNats:v.bestHeldoutNats==null?v.bestHeldoutNats:v.bestHeldoutNats,lastHeldoutNats:v.lastHeldoutNats==null?v.lastHeldoutNats:v.lastHeldoutNats,lastTrainNats:v.lastTrainNats==null?v.lastTrainNats:v.lastTrainNats,goal:v.goal==null?v.goal:v.goal}) as typeof v)),
	pauseRun: () => __TAURI_INVOKE<null>("pause_run"),
	resumeRun: () => __TAURI_INVOKE<null>("resume_run"),
	/**  Stop the active run. With `save`, a checkpoint is written first so nothing is lost. */
	stopRun: (save: boolean) => __TAURI_INVOKE<null>("stop_run", { save }),
	checkpointNow: () => __TAURI_INVOKE<null>("checkpoint_now"),
	sampleNow: () => __TAURI_INVOKE<null>("sample_now"),
	evalNow: () => __TAURI_INVOKE<null>("eval_now"),
	listRuns: () => __TAURI_INVOKE<RunSummary[]>("list_runs").then((v) => (v.map(i=>({...i,bestHeldoutNats:i.bestHeldoutNats==null?i.bestHeldoutNats:i.bestHeldoutNats,lastHeldoutNats:i.lastHeldoutNats==null?i.lastHeldoutNats:i.lastHeldoutNats,lastTrainNats:i.lastTrainNats==null?i.lastTrainNats:i.lastTrainNats,goal:i.goal==null?i.goal:i.goal})) as typeof v)),
	getRun: (runId: number) => __TAURI_INVOKE<RunSummary>("get_run", { runId }).then((v) => (({...v,bestHeldoutNats:v.bestHeldoutNats==null?v.bestHeldoutNats:v.bestHeldoutNats,lastHeldoutNats:v.lastHeldoutNats==null?v.lastHeldoutNats:v.lastHeldoutNats,lastTrainNats:v.lastTrainNats==null?v.lastTrainNats:v.lastTrainNats,goal:v.goal==null?v.goal:v.goal}) as typeof v)),
	/**  The full configuration a run was created with (for comparing runs and for forking one). */
	getRunConfig: (runId: number) => __TAURI_INVOKE<PresetConfig>("get_run_config", { runId }),
	/**  Export a saved model as a portable folder. Progress streams on `on_event`. */
	exportModel: (req: ExportRequest, onEvent: Channel<JobEvent>) => __TAURI_INVOKE<ExportResult>("export_model", { req, onEvent }),
	/**  Export a saved model as a safetensors file for other tools. Progress streams on `on_event`. */
	exportSafetensors: (req: ExportRequest, onEvent: Channel<JobEvent>) => __TAURI_INVOKE<ExportResult>("export_safetensors", { req, onEvent }),
	/**  Bring in a folder made by Export (from this or another computer), or the original program's weights folder. */
	importModel: (folder: string, onEvent: Channel<JobEvent>) => __TAURI_INVOKE<RunSummary>("import_model", { folder, onEvent }).then((v) => (({...v,bestHeldoutNats:v.bestHeldoutNats==null?v.bestHeldoutNats:v.bestHeldoutNats,lastHeldoutNats:v.lastHeldoutNats==null?v.lastHeldoutNats:v.lastHeldoutNats,lastTrainNats:v.lastTrainNats==null?v.lastTrainNats:v.lastTrainNats,goal:v.goal==null?v.goal:v.goal}) as typeof v)),
	/**  What importing a folder would do, before anything is copied. */
	previewImport: (folder: string) => __TAURI_INVOKE<ImportPreview>("preview_import", { folder }).then((v) => (({...v,model:v.model==null?v.model:v.model,heldoutNats:v.heldoutNats==null?v.heldoutNats:v.heldoutNats}) as typeof v)),
	getActiveRun: () => __TAURI_INVOKE<{
	id: number,
	uid: string,
	name: string,
	notes: string,
	status: RunState,
	preset: Preset,
	datasetId: number | null,
	datasetName: string | null,
	step: Step,
	charsRead: Chars,
	charsTotal: Chars | null,
	activeMs: Count,
	bestHeldoutNats: number | null,
	lastHeldoutNats: number | null,
	lastTrainNats: number | null,
	nExperts: number | null,
	verdict: Verdict | null,
	stage: string | null,
	backend: string | null,
	goal: Goal | null,
	error: string | null,
	createdAt: UnixMs,
	startedAt: UnixMs | null,
	endedAt: UnixMs | null,
} | null>("get_active_run").then((v) => (v==null?v:({...v,bestHeldoutNats:v.bestHeldoutNats==null?v.bestHeldoutNats:v.bestHeldoutNats,lastHeldoutNats:v.lastHeldoutNats==null?v.lastHeldoutNats:v.lastHeldoutNats,lastTrainNats:v.lastTrainNats==null?v.lastTrainNats:v.lastTrainNats,goal:v.goal==null?v.goal:v.goal}) as typeof v)),
	renameRun: (runId: number, name: string, notes: string) => __TAURI_INVOKE<RunSummary>("rename_run", { runId, name, notes }).then((v) => (({...v,bestHeldoutNats:v.bestHeldoutNats==null?v.bestHeldoutNats:v.bestHeldoutNats,lastHeldoutNats:v.lastHeldoutNats==null?v.lastHeldoutNats:v.lastHeldoutNats,lastTrainNats:v.lastTrainNats==null?v.lastTrainNats:v.lastTrainNats,goal:v.goal==null?v.goal:v.goal}) as typeof v)),
	/**  Delete a run's history, and optionally its saved model files from disk. */
	deleteRun: (runId: number, deleteFiles: boolean) => __TAURI_INVOKE<null>("delete_run", { runId, deleteFiles }),
	/**
	 *  Subscribe to the ordered live feed. Call once at startup and again after a webview reload; the returned snapshot
	 *  is the current state, so the UI can render immediately.
	 */
	subscribeLive: (onEvent: Channel<LiveMsg>) => __TAURI_INVOKE<LiveSnapshot>("subscribe_live", { onEvent }).then((v) => (({...v,run:v.run==null?v.run:({...v.run,bestHeldoutNats:v.run.bestHeldoutNats==null?v.run.bestHeldoutNats:v.run.bestHeldoutNats,lastHeldoutNats:v.run.lastHeldoutNats==null?v.run.lastHeldoutNats:v.run.lastHeldoutNats,lastTrainNats:v.run.lastTrainNats==null?v.run.lastTrainNats:v.run.lastTrainNats,goal:v.run.goal==null?v.run.goal:v.run.goal}),stage:v.stage==null?v.stage:({...v.stage,progress:v.stage.progress==null?v.stage.progress:({...v.stage.progress,total:v.stage.progress.total==null?v.stage.progress.total:v.stage.progress.total})}),lastEval:v.lastEval==null?v.lastEval:({...v.lastEval,domains:v.lastEval.domains.map(i=>i)}),lastPool:v.lastPool==null?v.lastPool:({...v.lastPool,resident:v.lastPool.resident.map(i=>i),haltingHist:v.lastPool.haltingHist.map(i=>i)}),insight:v.insight==null?v.insight:({...v.insight,eta:v.insight.eta==null?v.insight.eta:v.insight.eta,bitsPerChar:v.insight.bitsPerChar==null?v.insight.bitsPerChar:v.insight.bitsPerChar})}) as typeof v)),
	/**  Load a model from a run's saved progress and start a new conversation with it. */
	chatOpen: (req: ChatOpenRequest) => __TAURI_INVOKE<ChatSessionInfo>("chat_open", { req }),
	/**  Reload an earlier conversation's model so it can be continued. */
	chatResume: (sessionId: number) => __TAURI_INVOKE<ChatSessionInfo>("chat_resume", { sessionId }),
	/**  Send a message. The reply streams over `on_event`; the returned id is the stored user message. */
	chatSend: (sessionId: number, text: string, params: ChatParams, onEvent: Channel<ChatEvent>) => __TAURI_INVOKE<number>("chat_send", { sessionId, text, params, onEvent }),
	chatStop: (sessionId: number) => __TAURI_INVOKE<null>("chat_stop", { sessionId }),
	chatReset: (sessionId: number) => __TAURI_INVOKE<null>("chat_reset", { sessionId }),
	/**  Turn learning from this conversation on or off. Learning changes a separate copy, never the saved run. */
	chatSetLearn: (sessionId: number, enabled: boolean) => __TAURI_INVOKE<ChatSessionInfo>("chat_set_learn", { sessionId, enabled }),
	/**  Keep what the model learned in this chat as its own saved copy. */
	chatSaveAdapted: (sessionId: number) => __TAURI_INVOKE<CheckpointMeta>("chat_save_adapted", { sessionId }).then((v) => (({...v,heldoutNats:v.heldoutNats==null?v.heldoutNats:v.heldoutNats}) as typeof v)),
	chatClose: (sessionId: number) => __TAURI_INVOKE<null>("chat_close", { sessionId }),
	chatListSessions: () => __TAURI_INVOKE<ChatSessionInfo[]>("chat_list_sessions").then((v) => (v.map(i=>i) as typeof v)),
	chatGetMessages: (sessionId: number) => __TAURI_INVOKE<ChatMessage[]>("chat_get_messages", { sessionId }).then((v) => (v.map(i=>({...i,learnNatsBefore:i.learnNatsBefore==null?i.learnNatsBefore:i.learnNatsBefore,learnNatsAfter:i.learnNatsAfter==null?i.learnNatsAfter:i.learnNatsAfter,charsPerSec:i.charsPerSec==null?i.charsPerSec:i.charsPerSec})) as typeof v)),
	chatDeleteSession: (sessionId: number) => __TAURI_INVOKE<null>("chat_delete_session", { sessionId }),
	listDatasets: () => __TAURI_INVOKE<DatasetSummary[]>("list_datasets"),
	getDataset: (datasetId: number) => __TAURI_INVOKE<DatasetDetail>("get_dataset", { datasetId }),
	listStarters: () => __TAURI_INVOKE<StarterInfo[]>("list_starters"),
	/**  A quick look at what is being dragged over the window, before anything is scanned. */
	probePaths: (paths: string[]) => __TAURI_INVOKE<PathProbe[]>("probe_paths", { paths }),
	/**  Make a dataset from folders or files. Progress streams on `on_event`; the first message carries the job id. */
	addFolders: (paths: string[], laneMode: LaneMode, onEvent: Channel<JobEvent>) => __TAURI_INVOKE<DatasetDetail>("add_folders", { paths, laneMode, onEvent }),
	/**  Rebuild a dataset from its folders, optionally with a new train/test split. */
	rebuildDataset: (datasetId: number, split: {
	mode: SplitMode,
	/**  Share of every lane held out for validation, in percent (2.0 means 2 %). Clamped to 0.5..=10. */
	pct: number,
	/**  Seed for the file shuffle; the same inputs and seed always give the same split. */
	seed: number,
} | null, onEvent: Channel<JobEvent>) => __TAURI_INVOKE<DatasetDetail>("rebuild_dataset", { datasetId, split: split==null?split:split, onEvent }),
	getSplit: (datasetId: number) => __TAURI_INVOKE<SplitConfig>("get_split", { datasetId }),
	updateLane: (datasetId: number, lane: string, enabled: boolean | null, displayName: string | null, samplePrompt: string | null) => __TAURI_INVOKE<DatasetDetail>("update_lane", { datasetId, lane, enabled, displayName, samplePrompt }),
	/**  A random passage from one lane, so people can see what the model will read. */
	previewText: (datasetId: number, lane: string | null, nChars: number, seed: number) => __TAURI_INVOKE<TextPreview>("preview_text", { datasetId, lane, nChars, seed }),
	/**  Download or generate one of the built-in starter datasets. */
	installStarter: (starterId: string, onEvent: Channel<JobEvent>) => __TAURI_INVOKE<DatasetDetail>("install_starter", { starterId, onEvent }),
	generateArithmetic: (params: ArithmeticParams, onEvent: Channel<JobEvent>) => __TAURI_INVOKE<DatasetDetail>("generate_arithmetic", { params, onEvent }),
	deleteDataset: (datasetId: number, deleteFiles: boolean) => __TAURI_INVOKE<null>("delete_dataset", { datasetId, deleteFiles }),
	listJobs: () => __TAURI_INVOKE<JobInfo[]>("list_jobs").then((v) => (v.map(i=>({...i,progress:i.progress==null?i.progress:i.progress})) as typeof v)),
	/**  Stop a running download, scan or build. Whatever was finished is kept, so a download can continue later. */
	cancelJob: (jobId: string) => __TAURI_INVOKE<boolean>("cancel_job", { jobId }),
	/**
	 *  Chart series, downsampled on the server. Keys are metric names such as `train.nats`, or `eval.overall`,
	 *  `eval.train`, `eval.gap`, `eval.domain.<name>`.
	 */
	getSeries: (req: SeriesRequest) => __TAURI_INVOKE<SeriesData[]>("get_series", { req: ({...req,from:req.from==null?req.from:req.from,to:req.to==null?req.to:req.to}) }).then((v) => (v.map(i=>({...i,x:i.x.map(i=>i),y:i.y.map(i=>i==null?i:i),yLo:i.yLo.map(i=>i==null?i:i),yHi:i.yHi.map(i=>i==null?i:i)})) as typeof v)),
	getEvalPoints: (runId: number) => __TAURI_INVOKE<EvalPoint[]>("get_eval_points", { runId }).then((v) => (v.map(i=>({...i,trainNats:i.trainNats==null?i.trainNats:i.trainNats})) as typeof v)),
	/**  Names of the held-out domains scored during a run (one chart line each). */
	getEvalDomains: (runId: number) => __TAURI_INVOKE<string[]>("get_eval_domains", { runId }),
	getEvents: (runId: number, kinds: string[] | null) => __TAURI_INVOKE<RunEvent[]>("get_events", { runId, kinds }),
	/**  The sample round at `step`, or the latest when `step` is omitted. */
	getSamples: (runId: number, step: number | null) => __TAURI_INVOKE<{
	step: Step,
	chars: Chars,
	items: SampleItem[],
} | null>("get_samples", { runId, step }).then((v) => (v==null?v:({...v,items:v.items.map(i=>({...i,rawRep8:i.rawRep8==null?i.rawRep8:i.rawRep8,adaptedRep8:i.adaptedRep8==null?i.adaptedRep8:i.adaptedRep8}))}) as typeof v)),
	listSampleSteps: (runId: number) => __TAURI_INVOKE<StepAt[]>("list_sample_steps", { runId }),
	/**  The expert pool at `step` (nearest snapshot at or before it), or the latest when `step` is omitted. */
	getPoolSnapshot: (runId: number, step: number | null) => __TAURI_INVOKE<{
	step: Step,
	chars: Chars,
	nExperts: number,
	resident: ExpertInfo[],
	/**  Routing share of every expert in the pool, busiest first, quantised to 0..=255. */
	usage: number[],
	brakes: BrakeReport,
	/**  Histogram of rows used per character. */
	haltingHist: number[],
} | null>("get_pool_snapshot", { runId, step }).then((v) => (v==null?v:({...v,resident:v.resident.map(i=>i),haltingHist:v.haltingHist.map(i=>i)}) as typeof v)),
	listPoolSteps: (runId: number) => __TAURI_INVOKE<StepAt[]>("list_pool_steps", { runId }),
	listCheckpoints: (runId: number) => __TAURI_INVOKE<CheckpointInfo[]>("list_checkpoints", { runId }).then((v) => (v.map(i=>({...i,heldoutNats:i.heldoutNats==null?i.heldoutNats:i.heldoutNats})) as typeof v)),
};

/* Types */
/**  What the UI may suggest. Keys map to copy in `ui/src/content/`. */
export type AdviceKey = "keep_going" | "wait_for_first_check" | "read_more_text" | "add_more_varied_text" | "stop_and_keep_best" | "resume_from_best" | "lower_learning_rate" | "try_tiny_model";

export type AppError = { kind: "not_found"; detail: string } | { kind: "invalid"; detail: string } | { kind: "run_active" } | { kind: "no_active_run" } | { kind: "dataset_not_ready" } | { kind: "disk_full"; detail: {
	needBytes: Count,
	freeBytes: Count,
} } | { kind: "out_of_memory"; detail: {
	suggestedPreset: Preset | null,
} } | { kind: "backend_unavailable"; detail: string } | { kind: "network"; detail: string } | { kind: "checkpoint"; detail: string } | { kind: "io"; detail: string } | { kind: "db"; detail: string } | { kind: "engine"; detail: string } | { kind: "cancelled" };

export type AppInfo = {
	version: string,
	engineName: string,
	engineVersion: string,
	/**  True when the simulated engine is active (the UI shows an unmistakable badge). */
	isMock: boolean,
	dataDir: string,
	schemaVersion: number,
};

/**  Settings for the synthetic arithmetic lane. */
export type ArithmeticParams = {
	trainProblems: number,
	valProblems: number,
	seed: number,
	/**  Share of problems that carry a `<think> ... </think>` scratchpad, 0.0..=1.0. */
	notesFrac: number,
};

/**  One compute backend and whether it can be used on this machine. */
export type BackendInfo = {
	kind: BackendKind,
	name: string,
	available: boolean,
	/**  Plain-English reason when unavailable ("built without CUDA", "needs macOS 15 or newer", ...). */
	reason: string | null,
	/**  Memory the engine may use on this backend, in GB. */
	memBudgetGb: number,
	bf16Ok: boolean,
};

export type BackendKind = "metal" | "cuda" | "cpu";

export type Brake = {
	ok: boolean,
	why: string,
};

/**  The five conditions that must hold before the pool may grow. */
export type BrakeReport = {
	room: Brake,
	used: Brake,
	earning: Brake,
	fits: Brake,
	honest: Brake,
};

/**  Count of characters (bytes) read. */
export type Chars = number;

/**  What streams back while the model writes a reply. */
export type ChatEvent = 
/**  The model is being loaded from its save. */
{ type: "loading" } | 
/**  A piece of the reply, with what the model did to produce it. */
{ type: "chars"; text: string; rows: number[]; experts: number[] } | 
/**  The model learned from this exchange (only when learning is on). */
{ type: "learned"; natsBefore: number; natsAfter: number } | { type: "done"; messageId: number; chars: Count; charsPerSec: number } | { type: "error"; error: AppError };

export type ChatMessage = {
	id: number,
	role: ChatRole,
	content: string,
	learned: boolean,
	learnNatsBefore: number | null,
	learnNatsAfter: number | null,
	/**  Recurrent rows used for each generated character (model messages only). */
	rows: number[],
	charsPerSec: number | null,
	createdAt: UnixMs,
};

export type ChatMode = 
/**  The model continues whatever you type, like a story opening. */
"continue" | 
/**  Your text is wrapped as a chat turn and the model answers it. */
"conversation";

export type ChatOpenRequest = {
	runId: number,
	/**  A specific save to chat with; the latest save of the run when omitted. */
	checkpointId: number | null,
	mode: ChatMode,
};

export type ChatParams = {
	maxNew: number,
	/**  Repetition guard on. */
	adapt: boolean,
};

export type ChatRole = "user" | "model";

export type ChatSessionInfo = {
	id: number,
	title: string,
	runId: number | null,
	/**  Frozen at creation, e.g. "Tiny run 1, after 5.4M characters". */
	modelLabel: string,
	mode: ChatMode,
	learnEnabled: boolean,
	supportsLearn: boolean,
	/**  Memory this chat needs, in GB (the app warns when training and chat will not both fit). */
	needsGb: number,
	hasAdaptedCopy: boolean,
	createdAt: UnixMs,
};

export type CheckpointInfo = {
	id: number,
	step: Step,
	chars: Chars,
	kind: CheckpointKind,
	path: string,
	bytes: Count,
	heldoutNats: number | null,
	nExperts: number | null,
	isBest: boolean,
	pinned: boolean,
	createdAt: UnixMs,
};

export type CheckpointKind = "auto" | "manual" | "best" | "final" | "stop" | "imported";

export type CheckpointMeta = {
	step: Step,
	chars: Chars,
	kind: CheckpointKind,
	/**  Directory name relative to the run directory. */
	path: string,
	bytes: Count,
	heldoutNats: number | null,
	nExperts: number,
	engineFormat: number,
};

/**  A non-negative size or count (bytes, rows). */
export type Count = number;

export type CreateRunRequest = {
	name: string | null,
	preset: Preset,
	/**  Overrides for the preset's configuration (advanced settings). `None` uses the preset as is. */
	model: ModelConfig | null,
	train: TrainConfig | null,
	datasetId: number | null,
	goal: Goal | null,
};

export type DatasetDetail = {
	summary: DatasetSummary,
	lanes: LaneInfo[],
	skipped: SkippedSummary,
	warnings: string[],
};

export type DatasetKind = 
/**  Downloaded or generated from the built-in starter list. */
"starter" | 
/**  Built from the user's own folders. */
"linked" | 
/**  Generated locally (synthetic text). */
"generated" | 
/**  Shipped inside the app. */
"bundled";

export type DatasetStatus = 
/**  Created but not yet scanned or prepared. */
"draft" | "scanning" | 
/**  Downloading, generating or linking files. */
"preparing" | "ready" | "error";

export type DatasetSummary = {
	id: number,
	name: string,
	kind: DatasetKind,
	/**  Set when this dataset was installed from the starter list. */
	starterId: string | null,
	status: DatasetStatus,
	trainBytes: Count,
	valBytes: Count,
	lanes: number,
	license: string | null,
	attribution: string | null,
	sourceUrl: string | null,
	error: string | null,
	createdAt: UnixMs,
};

/**  Greedy decoding with a repetition trace ("adapted" reading in the original). */
export type DecodingConfig = {
	adaptStrength: number,
	adaptDecay: number,
	repPenalty: number,
};

export type DomainScore = {
	domain: string,
	nats: number,
	se: number,
	nChars: Count,
};

/**  Predicted cost of a configuration on this machine. Numbers marked `measured` came from a benchmark here. */
export type Estimate = {
	paramsStart: Count,
	paramsFullPool: Count,
	/**  Memory resident on the accelerator while training, in GB. */
	gpuGb: number,
	ramGb: number,
	/**  Disk used by the expert pool and checkpoints at the growth ceiling, in GB. */
	diskGb: number,
	charsPerSec: number,
	/**  True when `chars_per_sec` came from a benchmark on this machine instead of a formula. */
	measured: boolean,
	fit: Fit,
	notes: string[],
};

export type Eta = {
	seconds: number,
	chars: number,
};

/**  One held-out evaluation, in nats per character. */
export type EvalPoint = {
	chars: number,
	nats: number,
	se: number,
	trainNats: number | null,
};

/**  A held-out evaluation round: the model is scored on text it has never trained on. */
export type EvalResult = {
	step: Step,
	chars: Chars,
	overallNats: number,
	overallSe: number,
	trainNatsEma: number,
	domains: DomainScore[],
};

export type ExpertInfo = {
	uid: number,
	/**  GPU slot when resident. */
	slot: number | null,
	gate: number,
	/**  Share of routing this expert received recently (0..1). */
	useShare: number,
	admits: number,
	ageChars: Chars,
	onTrial: boolean,
	/**  Fraction of the survival window it has gone unused (0..1). */
	staleness: number,
	dying: boolean,
};

export type ExportRequest = {
	runId: number,
	/**  A specific save; the best or latest one when omitted. */
	checkpointId: number | null,
	/**  Folder the export is created inside. */
	destDir: string,
};

export type ExportResult = {
	/**  The folder that was created. */
	path: string,
	bytes: Count,
	files: Count,
};

/**  How well a configuration fits the selected backend. */
export type Fit = "comfortable" | "tight" | "wont_fit";

/**
 *  Continue a run's saved model as a new run, optionally with different training settings or different text.
 *  The model's shape is fixed by the save; everything about *how it trains* may change.
 */
export type ForkRunRequest = {
	runId: number,
	/**  A specific save; the best or latest one when omitted. */
	checkpointId: number | null,
	name: string | null,
	/**  The text to read; the original run's text when omitted. */
	datasetId: number | null,
	/**  New training settings; the original run's when omitted. */
	train: TrainConfig | null,
	goal: Goal | null,
};

/**  When a run should stop by itself. */
export type Goal = { type: "minutes"; value: number } | { type: "chars"; value: Chars } | 
/**  Stop when the held-out score reaches this many bits per character. */
{ type: "target_bits"; value: number } | { type: "until_stopped" };

/**  Pool growth settings (new experts are born by recombining existing ones). */
export type GrowthConfig = {
	everyChars: number,
	k: number,
	maxGap: number,
	dyingFracMax: number,
	maxInFlight: number,
	keepRatioMin: number,
	recentMult: number,
	maxDiskGb: number,
	memFrac: number,
	birthGate: number,
};

export type GrowthEvent = { type: "born"; uid: number; parents: number[] } | { type: "pruned"; uid: number; reason: string } | { type: "blocked"; brakes: BrakeReport };

export type HardwareInfo = {
	os: string,
	cpu: string,
	cores: number,
	ramGb: number,
	ramFreeGb: number,
	diskFreeGb: number,
	backends: BackendInfo[],
	/**  Backend the engine will use (best available unless the user chose one). */
	selected: BackendKind,
};

export type ImportIssue = {
	severity: ImportSeverity,
	/**  Plain English, ready to show. */
	message: string,
};

/**  Where a model folder offered for import comes from. */
export type ImportKind = 
/**  A folder made by this app's Export. */
"portable" | 
/**  The weights folder of the original Python program (mini-AGI). */
"python";

/**  What importing a folder would do, shown before anything is copied. */
export type ImportPreview = {
	path: string,
	kind: ImportKind,
	importable: boolean,
	/**  One plain-English sentence about the model. */
	summary: string,
	issues: ImportIssue[],
	/**  A suggested name for the new run. */
	name: string,
	preset: Preset,
	model: ModelConfig | null,
	step: Step,
	chars: Chars,
	heldoutNats: number | null,
	nExperts: number,
	bytes: Count,
};

export type ImportSeverity = 
/**  The model cannot be imported as it is. */
"blocker" | 
/**  It can be imported, but something changes or is left behind. */
"warning" | "note";

export type Insight = {
	report: VerdictReport,
	eta: Eta | null,
	milestone: Milestone,
	/**  Latest held-out score in bits per character. */
	bitsPerChar: number | null,
};

/**  Messages on a job's live channel. */
export type JobEvent = { type: "progress"; jobId: string; progress: JobProgress } | { type: "state"; jobId: string; state: JobState; error: string | null };

/**  A long-running task (scanning a folder, downloading, generating text) the UI can follow. */
export type JobInfo = {
	id: string,
	/**  `scan`, `download`, `generate`, `prepare`... */
	kind: string,
	state: JobState,
	/**  What it is about, e.g. `dataset:12`. */
	subject: string | null,
	/**  0.0..=1.0 when known. */
	progress: number | null,
	message: string | null,
	error: string | null,
	createdAt: UnixMs,
	updatedAt: UnixMs,
};

/**  Progress of a background job (download, generate, link files). */
export type JobProgress = {
	done: number,
	total: number | null,
	/**  What `done` and `total` count: `"bytes"`, `"files"` or `"problems"`. */
	unit: string,
	/**  One plain-English line: "Downloading TinyStories-train.txt". */
	message: string,
	bytesPerSec: number | null,
	etaSeconds: number | null,
};

export type JobState = "queued" | "running" | "paused" | "done" | "failed" | "cancelled";

/**  One lane of a dataset, as shown in the lane table. */
export type LaneInfo = {
	/**  Folder-safe name (`[a-z0-9_-]`), also the directory name under `train/` and `val/`. */
	name: string,
	/**  Human-friendly name (the original folder name). */
	displayName: string,
	/**  Fixed colour slot. 0..=7 are the eight lane colours, 8 and above fold into the shared "Other" colour. */
	colorSlot: number,
	/**  Whether the lane is read during training. */
	enabled: boolean,
	nFiles: Count,
	trainBytes: Count,
	valFiles: Count,
	valBytes: Count,
	/**  A prompt that suits this lane, offered when sampling from the model. */
	samplePrompt: string | null,
};

/**  How the folders a user drops are mapped to lanes. */
export type LaneMode = 
/**  Pick the best of the four rules (mini-AGI layout, one lane per subfolder, one lane, one lane per root). */
"auto" | 
/**  Everything becomes a single lane. */
"one_lane" | 
/**  Each top-level subfolder becomes a lane, whatever the share of loose files. */
"per_folder";

/**  One ordered stream carries everything for the active run to the UI. */
export type LiveMsg = { type: "stage"; runId: number; info: StageInfo; at: UnixMs } | { type: "state"; runId: number; state: RunState; reason: string | null } | 
/**  At most about 4 per second; tiny. */
{ type: "pulse"; runId: number; step: Step; chars: Chars; charsTotal: Chars | null; trainNatsEma: number; readCps: number; activeMs: Count; schedule: Schedule } | 
/**  At most about 1 per second, averaged. */
{ type: "ticks"; runId: number; points: TickPoint[] } | { type: "eval"; runId: number; result: EvalResult } | { type: "samples"; runId: number; round: SampleRound } | { type: "pool"; runId: number; snapshot: PoolSnapshot } | { type: "growth"; runId: number; event: GrowthEvent } | { type: "plasticity"; runId: number; event: PlasticityEvent } | { type: "insight"; runId: number; insight: Insight } | { type: "checkpoint"; runId: number; checkpoint: CheckpointMeta } | { type: "warning"; runId: number; code: string; message: string; hint: string | null } | { type: "error"; runId: number; error: AppError; fatal: boolean };

/**  Current state of the live feed, returned on (re)subscribe so a reloaded UI recovers immediately. */
export type LiveSnapshot = {
	run: RunSummary | null,
	stage: StageInfo | null,
	lastEval: EvalResult | null,
	lastPool: PoolSnapshot | null,
	insight: Insight | null,
	schedule: Schedule | null,
};

/**  Where the model is on the road from random guessing to fluent text. */
export type Milestone = {
	/**  0-based index of the current milestone. */
	index: number,
	total: number,
	key: string,
};

/**  Shape of the network. Fixed once the model exists (the UI locks these fields on resume). */
export type ModelConfig = {
	dModel: number,
	nHead: number,
	/**  Hidden width of the dense (trunk) SwiGLU blocks. */
	dFf: number,
	nPrelude: number,
	nRecur: number,
	nCoda: number,
	/**  Maximum number of recurrent "rows" (thinking steps) per character. */
	maxSteps: number,
	minSteps: number,
	haltPrior: number,
	haltThresh: number,
	haltFreeze: boolean,
	ponderBeta: number,
	bpttWindow: number,
	/**  Mean number of rows sampled per training step (Poisson). */
	trainStepsMean: number,
	/**  Longest context the position tables are built for. */
	block: number,
	vocabSize: number,
	/**  Experts the pool starts with. */
	poolExperts: number,
	/**  Hard ceiling on the number of experts the pool may grow to. */
	poolMax: number,
	/**  Hidden width of one expert. */
	poolDFf: number,
	poolDepth: number,
	poolTopK: number,
};

/**  How the mixture-of-experts layer is computed. */
export type MoeMode = 
/**  One wide feed-forward over all resident experts with per-token gains. Simple, no dropped tokens. Used for Tiny. */
"dense_masked" | 
/**  Switch-style capacity dispatch: only the chosen experts run. Used for Small and Full. */
"sparse_dispatch";

/**  Quick answer about something the user is dragging over the window, before any real scan. */
export type PathProbe = {
	path: string,
	isDir: boolean,
	/**  Files seen during the (time-boxed) walk; a lower bound when `exact` is false. */
	approxFiles: Count,
	/**  False when the walk stopped at its time budget. */
	exact: boolean,
	/**  True when the folder has a `train/` subfolder, i.e. it is already in the shape the engine reads. */
	looksLikeMiniAgiLayout: boolean,
};

export type PlasticityEvent = {
	rateScale: number,
	evidenceT: number,
	reason: string,
	jumped: boolean,
};

/**  State of the expert pool at a moment in training. */
export type PoolSnapshot = {
	step: Step,
	chars: Chars,
	nExperts: number,
	resident: ExpertInfo[],
	/**  Routing share of every expert in the pool, busiest first, quantised to 0..=255. */
	usage: number[],
	brakes: BrakeReport,
	/**  Histogram of rows used per character. */
	haltingHist: number[],
};

/**  Numeric precision of matrix multiplications. Master weights are always f32. */
export type Precision = "f32" | "f16" | "bf16";

/**  Model size presets. `Custom` means the user edited advanced settings; `Imported` is a checkpoint from elsewhere. */
export type Preset = "tiny" | "small" | "full" | "custom" | "imported";

/**  A preset's full configuration, for the Setup screen. */
export type PresetConfig = {
	preset: Preset,
	model: ModelConfig,
	train: TrainConfig,
};

export type PresetFit = {
	preset: Preset,
	estimate: Estimate,
};

export type Progress = {
	done: number,
	total: number | null,
	unit: string,
};

/**  Pruning settings (experts nothing has addressed for a long time are removed). */
export type PruneConfig = {
	survivalChars: number,
	dyingAt: number,
};

export type Recommendation = {
	preset: Preset,
	reasons: string[],
	fits: PresetFit[],
};

/**  A point of interest on the timeline (checkpoint, pause, growth, warning...). */
export type RunEvent = {
	id: number,
	step: Step,
	chars: Chars,
	at: UnixMs,
	kind: string,
	expertUid: number | null,
	brake: string | null,
	payload: string | null,
};

export type RunState = "created" | "preparing" | "running" | "paused" | "stopping" | "completed" | "stopped" | "failed" | 
/**  The app was closed or crashed while the run was active. */
"interrupted" | "imported";

export type RunStorage = {
	runId: number,
	name: string,
	bytes: Count,
};

export type RunSummary = {
	id: number,
	uid: string,
	name: string,
	notes: string,
	status: RunState,
	preset: Preset,
	datasetId: number | null,
	datasetName: string | null,
	step: Step,
	charsRead: Chars,
	charsTotal: Chars | null,
	activeMs: Count,
	bestHeldoutNats: number | null,
	lastHeldoutNats: number | null,
	lastTrainNats: number | null,
	nExperts: number | null,
	verdict: Verdict | null,
	stage: string | null,
	backend: string | null,
	goal: Goal | null,
	error: string | null,
	createdAt: UnixMs,
	startedAt: UnixMs | null,
	endedAt: UnixMs | null,
};

export type SampleItem = {
	domain: string,
	prompt: string,
	/**  Plain greedy continuation. */
	raw: string,
	/**  Greedy continuation with the repetition trace switched on. */
	adapted: string,
	rawRep8: number | null,
	adaptedRep8: number | null,
	note: string | null,
};

/**  What the model writes for each prompt at a point in training ("watch it learn to write"). */
export type SampleRound = {
	step: Step,
	chars: Chars,
	items: SampleItem[],
};

/**  When the next scheduled things will happen, so the UI can say "next check-up in 3:12". */
export type Schedule = {
	nextEvalChars: Chars | null,
	nextSampleMs: Count | null,
	nextCheckpointMs: Count | null,
	nextGrowthChars: Chars | null,
};

/**  Columnar chart data: parallel arrays, with a min/max envelope per bucket so spikes survive downsampling. */
export type SeriesData = {
	key: string,
	x: number[],
	y: (number | null)[],
	yLo: (number | null)[],
	yHi: (number | null)[],
	/**  Steps per bucket (1 = raw). */
	bucket: number,
};

export type SeriesRequest = {
	runId: number,
	/**  Metric names such as `train.nats`, `lr.scale`. */
	keys: string[],
	x: XAxis,
	from: number | null,
	to: number | null,
	maxPoints: number,
};

/**  One file that was not used, with the reason in plain words. */
export type SkippedExample = {
	path: string,
	reason: string,
};

/**  What a folder scan left out, counted by reason. `examples` holds at most 50 entries. */
export type SkippedSummary = {
	/**  Images, archives, executables, or files whose content is not text. */
	binary: number,
	empty: number,
	/**  UTF-16 or UTF-32 text (recognised by its byte-order mark); the engine reads UTF-8 only. */
	utf16: number,
	tooLarge: number,
	/**  Files or folders that could not be opened (permissions, vanished mid-scan). */
	unreadable: number,
	examples: SkippedExample[],
};

/**  How a dataset's text is divided into training and validation. */
export type SplitConfig = {
	mode: SplitMode,
	/**  Share of every lane held out for validation, in percent (2.0 means 2 %). Clamped to 0.5..=10. */
	pct: number,
	/**  Seed for the file shuffle; the same inputs and seed always give the same split. */
	seed: number,
};

export type SplitMode = 
/**  Hold a small share of the files (or the end of a big file) out for validation. */
"auto" | 
/**  Use the `val/` folder the dataset already has, exactly as it is. */
"folder";

/**  Coarse phase of a run, shown in the "What's happening now" banner. */
export type Stage = "idle" | "preparing_data" | "creating_model" | "loading_checkpoint" | 
/**  The main loop: read a chunk, guess each next character, learn from the mistakes. */
"reading" | "evaluating" | "sampling" | "grow_prune" | "checkpointing" | "paused" | "stopping" | "finished" | "failed";

export type StageInfo = {
	stage: Stage,
	detail: string | null,
	progress: Progress | null,
};

/**  A starter dataset the app can install. */
export type StarterInfo = {
	id: string,
	title: string,
	description: string,
	/**  Approximate size on disk once installed. */
	sizeBytes: Count,
	license: string,
	attribution: string,
	sourceUrl: string,
	/**  True when no network is needed (generated locally or bundled). */
	offline: boolean,
};

/**  Optimizer step counter. */
export type Step = number;

/**  A point on the training timeline (a step and the characters read by then). */
export type StepAt = {
	step: Step,
	chars: Chars,
};

/**  Where the app's disk space goes, in bytes. */
export type StorageUsage = {
	dataDir: string,
	datasetsBytes: Count,
	runsBytes: Count,
	chatsBytes: Count,
	databaseBytes: Count,
	freeBytes: Count,
	/**  Disk used by each run (largest first), so people can see what to delete. */
	perRun: RunStorage[],
};

/**  A random passage from a lane, for the "peek inside" panel. */
export type TextPreview = {
	/**  Path of the file relative to the lane. */
	file: string,
	/**  Byte offset of the passage inside the file. */
	offset: Count,
	text: string,
};

/**  A once-per-second sample of the training curves, persisted and charted. */
export type TickPoint = {
	step: Step,
	chars: Chars,
	/**  Active training time in ms (pauses excluded). */
	tMs: Count,
	trainNats: number,
	gradNorm: number,
	lrScale: number,
	lrEffective: number,
	readCps: number,
	writeCps: number | null,
	contextNow: number,
	nExperts: number,
	avgRows: number,
	rep8Pct: number | null,
};

/**  Everything about how training proceeds. Can differ between runs of the same model. */
export type TrainConfig = {
	lr: number,
	/**  Trunk (embeddings, attention, norms, halting) learns at `lr * trunk_lr_mult`. */
	trunkLrMult: number,
	weightDecay: number,
	beta1: number,
	beta2: number,
	clip: number,
	/**  Characters read per optimizer step. */
	chunk: number,
	/**  Characters per passage visit in a lane. */
	passage: number,
	shuffleSeed: number,
	poolAux: number,
	/**  Experts on the accelerator at once. */
	resident: number,
	/**  Experts cached in RAM. */
	ramCache: number,
	capacityFactor: number,
	exploreBias: number,
	exploreSteps: number,
	contextStart: number,
	contextEnd: number,
	contextStep: number,
	contextGrowEveryChars: number,
	contextGainMin: number,
	contextEveryChars: number,
	growth: GrowthConfig,
	prune: PruneConfig,
	decoding: DecodingConfig,
	/**  Minutes between held-out evaluation + sample rounds. */
	sampleEveryMin: number,
	/**  Minutes between automatic checkpoints. */
	saveEveryMin: number,
	/**  Held-out characters scored per domain in a full evaluation. */
	evalChars: number,
	precision: Precision,
	moeMode: MoeMode,
	/**  Recompute rows in the backward pass instead of storing activations (needed for Full). */
	rowCheckpointing: boolean,
};

/**  Unix time in milliseconds. */
export type UnixMs = number;

export type Verdict = 
/**  Too few evaluations to say. */
"warming_up" | "learning" | "plateau" | 
/**  Memorising the training text: it does better on text it has seen than text it has not. */
"overfitting" | 
/**  The loss jumped up or became invalid. */
"diverging";

export type VerdictReport = {
	verdict: Verdict,
	/**  Relative improvement of the held-out score over the recent window (positive = better). */
	changePct: number,
	advice: AdviceKey[],
};

/**  What a chart axis measures. */
export type XAxis = "chars" | "step" | "time";

