[package]
name = "minagi-cli"
description = "Command line tools: train, benchmarks"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
minagi-core.workspace = true
minagi-types.workspace = true
anyhow = "1"
tempfile = "3"
